[phases.setup]
nixPkgs = ["glib", "nss", "nspr", "atk", "at-spi2-atk", "cups", "dbus", "expat", "libdrm", "libxcb", "libxkbcommon", "libx11", "libxcomposite", "libxdamage", "libxext", "libxfixes", "libxrandr", "mesa", "pango", "cairo", "alsa-lib"]

[phases.install]
cmds = ["npm install", "npx playwright install --with-deps chromium"]